import { DEFAULT_EXAM_DATE } from "./dateUtils";
import type { PlannerData, Subject, Task } from "./types";

/** order 决定每日排程的先后：英语最早，政治最晚 */
export const DEFAULT_SUBJECTS: Subject[] = [
  { id: "en", name: "英语", colorId: "pink", order: 1 },
  { id: "intro", name: "社会政策概论", colorId: "amber", order: 2 },
  { id: "topic", name: "社会政策专题", colorId: "green", order: 3 },
  { id: "method", name: "社会研究方法", colorId: "cyan", order: 4 },
  { id: "stat", name: "社会统计", colorId: "violet", order: 5 },
  { id: "pol", name: "政治", colorId: "orange", order: 9 },
];

export const DEFAULT_TASKS: Task[] = [
  {
    id: "vocab",
    subjectId: "en",
    name: "单词",
    dailyHours: 1,
    startDate: "2026-09-15",
    endDate: "2026-12-18",
    method: "新词、昨日、三日前循环复习。",
    colorId: "pink",
  },
  {
    id: "sentence",
    subjectId: "en",
    name: "长难句",
    dailyHours: 0.5,
    startDate: "2026-09-15",
    endDate: "2026-11-13",
    method: "手写拆主干，翻译后对照修正。",
    colorId: "rose",
  },
  {
    id: "en-course",
    subjectId: "en",
    name: "课程",
    dailyHours: 1.5,
    startDate: "2026-09-15",
    endDate: "2026-12-04",
    method: "阅读、新题型、完形、翻译、作文分阶段推进。",
    colorId: "magenta",
  },
  {
    id: "en-test",
    subjectId: "en",
    name: "刷题",
    dailyHours: 1.5,
    startDate: "2026-10-03",
    endDate: "2026-12-18",
    method: "精读优先，后期加入整套限时。",
    colorId: "fuchsia",
  },
  {
    id: "en-essay",
    subjectId: "en",
    name: "背作文模版",
    dailyHours: 0.5,
    startDate: "2026-11-14",
    endDate: "2026-12-18",
    method: "大小作文各一套自己的模板，默写检查。",
    colorId: "coral",
  },
  {
    id: "intro-note",
    subjectId: "intro",
    name: "整理笔记",
    dailyHours: 2,
    startDate: "2026-09-15",
    endDate: "2026-10-23",
    method: "看原文、理逻辑、当场修订材料。",
    colorId: "amber",
  },
  {
    id: "intro-recite",
    subjectId: "intro",
    name: "三轮背诵",
    dailyHours: 1.5,
    startDate: "2026-09-26",
    endDate: "2026-12-18",
    method: "框架、关键词、完整复述三轮推进。",
    colorId: "yellow",
  },
  {
    id: "topic-note",
    subjectId: "topic",
    name: "整理笔记",
    dailyHours: 1.8,
    startDate: "2026-09-15",
    endDate: "2026-10-23",
    method: "按五问整理长期政策领域。",
    colorId: "green",
  },
  {
    id: "topic-recite",
    subjectId: "topic",
    name: "三轮背诵",
    dailyHours: 1.5,
    startDate: "2026-09-26",
    endDate: "2026-12-18",
    method: "按最小结构背，并对照真题口答。",
    colorId: "lime",
  },
  {
    id: "method-focus",
    subjectId: "method",
    name: "梳理重点",
    dailyHours: 1.2,
    startDate: "2026-09-15",
    endDate: "2026-10-16",
    method: "抓特点、局限与适用问题。",
    colorId: "cyan",
  },
  {
    id: "method-recite",
    subjectId: "method",
    name: "三轮背诵",
    dailyHours: 1,
    startDate: "2026-09-26",
    endDate: "2026-12-18",
    method: "结合真题形成答题表达。",
    colorId: "teal",
  },
  {
    id: "stat-course",
    subjectId: "stat",
    name: "看课程",
    dailyHours: 1.5,
    startDate: "2026-10-03",
    endDate: "2026-11-20",
    method: "公式与适用条件同步整理。",
    colorId: "violet",
  },
  {
    id: "stat-test",
    subjectId: "stat",
    name: "针对性做题",
    dailyHours: 1.5,
    startDate: "2026-10-17",
    endDate: "2026-12-18",
    method: "先计算题，12月再集中选择题。",
    colorId: "purple",
  },
  {
    id: "pol-video",
    subjectId: "pol",
    name: "看视频课程",
    dailyHours: 1,
    startDate: "2026-09-15",
    endDate: "2026-10-30",
    method: "听课后合书复述框架。",
    colorId: "orange",
  },
  {
    id: "pol-test",
    subjectId: "pol",
    name: "刷题",
    dailyHours: 1.2,
    startDate: "2026-09-26",
    endDate: "2026-12-04",
    method: "选择题当日清，按错因归类。",
    colorId: "red",
  },
  {
    id: "xiao4",
    subjectId: "pol",
    name: "背诵肖四大题",
    dailyHours: 2,
    startDate: "2026-11-21",
    endDate: "2026-12-18",
    method: "先背题目框架，再补关键词。",
    colorId: "coral",
  },
];

export const DEFAULT_PLANNED_HOURS = 11;

export const INITIAL_DATA: PlannerData = {
  subjects: DEFAULT_SUBJECTS,
  tasks: DEFAULT_TASKS,
  dayPlans: {},
  plannedHours: {},
  weekTexts: {},
  dayNotes: {},
  dayMiscs: {},
  eventName: "考研",
  examDate: DEFAULT_EXAM_DATE,
  capacity: 12,
  weekStart: "sat",
};
